---
- name: Copy instanceArgsFile.args to infinys_root directory
  template:
    src: "instanceArgsFile.args.j2"
    dest: "{{ infinys_dir }}/instanceArgsFile.args"
    owner: "{{ RBM_BE_USER }}"
    group: "{{ RBM_BE_GROUP }}"
    mode: 0664

- name: Update gparams
  include_role:
    name: service_rtcc
    tasks_from: merge_gparams.yaml
  vars:
    merge_gparams_lines:
      - { param_name: "SYSdomainingStrategy", type: "STRING", start_dtm: "to_date('01-JAN-70','DD-MON-RR')", value: "T" }
      - { param_name: "SYSonlineChargingAISInUseBoo", type: "STRING", start_dtm: "to_date('01-JAN-95','DD-MON-RR')", value: "F" }
      - { param_name: "SYSonlineChargingCachesInUseBoo", type: "STRING", start_dtm: "to_date('01-JAN-95','DD-MON-RR')", value: "T" }
      - { param_name: "LCXMbackendDatabaseServiceName", type: "STRING", start_dtm: "to_date(  SYSDATE,  'DD-MON-RR')", value: "{{ be_oracle_service_name }}" }

- name: Install Caches
  register: caches
  shell: |
    source ./infinys.env
    rm -f $INFINYS_LOGS/RBIUH/CacheInstallStatus
    ksh -x $INFINYS_ROOT/RB/bin/CacheInstanceInstall.ksh {{ '-t '~oracle_tablespaces.geneva_admin_rtcc_default_tbs if oracle_tablespaces.geneva_admin_rtcc_default_tbs is defined else '' }} -f {{ infinys_dir }}/instanceArgsFile.args
    if [[ $? -ne 0 ]];then
        exit 1
    fi
  args:
    chdir: "{{ infinys_dir }}"
  environment:
    UNIF_PASSWORD_ARG: "{{ unif_password }}"
    GENEVA_PASSWORD_ARG: "{{ rb_logon_password }}"
    PF_ORA_LOGON_PASSWORD_ARG: "{{ pf_schema_password }}"
    PF_INITAL_USER_PASSWORD_ARG: "{{ pf_initial_user_password }}"
    PF_CONTAINER_USER_PASSWORD_ARG: "{{ pf_container_user_password }}"
    PF_SEC_SCHEMA_PASSWORD_ARG: "{{ pf_sec_schema_password }}"
    PF_AUDIT_PASSWORD_ARG: "{{ pf_audit_password }}"
    INFINYS_PATH: "{{ infinys_dir }}"
    DB_UTIL_PATH: "{{ infinys_dir }}/UTILITIES/Installation/dba_install"
    RB_SCHEMA_PATH: "{{ infinys_dir }}/RB/schema/olc"
    INPUT_FILE: "{{ infinys_dir }}/instanceArgsFile.args"
    PKG_ROOT: "{{ kits_dir }}"
  tags:
    - skip_ansible_lint

- name: Display output
  debug:
    msg: "{{ caches.stdout }}"
  when: not ansible_check_mode
