---

- name: Resolve path to the script template
  set_fact:
    cleanup_rbm_database_template_file_path: "{{ role_path }}/templates/cleanup_rbm_database.sql.j2"

- name: Copy and call cleanup_rbm_database.sql on hosts {{ cleanup_rbm_database_host_list }}
  include_role:
    name: service_rbm
    tasks_from: cleanup_execute_sql_script.yaml
  vars:
    cleanup_execute_sql_script_template_file: "{{ cleanup_rbm_database_template_file_path }}"
    cleanup_execute_sql_script_dest_file: "{{ cleanup_rbm_database_file_dest_dir }}/cleanup_rbm_database.sql"
    cleanup_execute_sql_script_host_list: "{{ cleanup_rbm_database_host_list }}"
