---
- name: "ECA Status Check"
  no_log: yes
  wait_for:
    host: "{{ web_server_host }}"
    port: "{{ web_server_port }}"
    state: stopped
    sleep: 5
    delay: 5
    timeout: 150
    msg: "this is started"
  ignore_errors: yes
  register: check_stopped

- name: "Info message"
  debug:
    msg: "ECA has already been stopped"
  when:
    - not check_stopped.failed

- block:
    - name: "Execute infinysctl to stop ECA admin server"
      shell: |
        cd {{ infinys_dir }}
        source {{ infinys_dir }}/infinys.env
        infinysctl stop
      environment:
        PF_USER_PASSWORD: "{{ unif_password }}"
        INF_SCHEMA_PASSWORD: "{{ inf_user_password }}"
        PF_SCHEMA_PASSWORD: "{{ pf_schema_password }}"
        PF_SEC_SCHEMA_PASSWORD: "{{ pf_sec_schema_password }}"
      tags:
        - skip_ansible_lint

    - name: "Wait for port {{ web_server_port }}"
      wait_for:
        host: "{{ web_server_host }}"
        port: "{{ web_server_port }}"
        state: stopped
        sleep: 10
        delay: 30
        timeout: 300
        msg: "Failed to stop ECA on {{ web_server_port }} port"

    - name: "Info message"
      debug:
        msg: "ECA stopped"
  when:
    - check_stopped.failed
