---
# path of custom lib *.so files
rtcc_deploy_custom_lib_dir: "{{ infinys_dir }}/RB/CUSTOM/LIB"
rtcc_trace_shm_dir: "{{ HA_ROOT }}/logs/dynamic_traces"
# path of logs directory
rtcc_ais_log_dir: "{{ infinys_dir }}/LOGS"

rtcc_database_user: geneva_admin
rtcc_database_password: "{{ rb_logon_password }}"
rtcc_prov_log_dir: "{{ HA_ROOT }}/logs/instantiation"

rtcc_rolling_update: no
