---
- name: Copy gparams_update.sql file
  template:
    src: "merge_gparams.sql.j2"
    dest: "{{ infinys_dir }}/scripts/merge_gparams.sql"
    owner: "{{ RBM_BE_USER }}"
    group: "{{ RBM_BE_GROUP }}"
    mode: 0664

- name: Execute script to merge gparams
  shell: |
    source ./infinys.env
    sqlplus -s geneva_admin/$rbm_rb_logon_password@{{ be_oracle_service_name }} @scripts/merge_gparams.sql
  args:
    chdir: "{{ infinys_dir }}"
  environment:
    rbm_rb_logon_password: "{{ rb_logon_password }}"
  register: merge_gparams
  tags:
    - skip_ansible_lint

- debug:
    msg: "{{ merge_gparams.stdout }}"
  when: not ansible_check_mode

- name: Remove script for merge gparams
  file:
    state: absent
    path: "{{ infinys_dir }}/scripts/merge_gparams.sql"
