---
- name: Set CACHE_DATA_SET_CNTRL_STATE = 3
  shell: |
    source ./infinys.env
    sqlplus -s geneva_admin/$rbm_rb_logon_password@{{ be_oracle_service_name }} <<EOL
    update CACHEDATASET set CACHE_DATA_SET_CNTRL_STATE = 3;
    commit;
    exit;
    EOL
  environment:
    rbm_rb_logon_password: "{{ rb_logon_password }}"
  args:
    chdir: "{{ infinys_dir }}"
  register: cache_dataset_sql_3
  tags:
    - skip_ansible_lint

- debug:
    msg: "{{ cache_dataset_sql_3.stdout }}"
  when: not ansible_check_mode

- name: Copy drop_triggers_procedures.sql
  template:
    src: drop_triggers_procedures.sql.j2
    dest: "{{ infinys_dir }}/scripts/drop_triggers_procedures.sql"
    owner: "{{ RBM_BE_USER }}"
    group: "{{ RBM_BE_GROUP }}"
    mode: 0664

- name: Drop triggers (Execute sql file)
  shell: |
    source ./infinys.env
    sqlplus -s geneva_admin/$rbm_rb_logon_password@{{ be_oracle_service_name }} @scripts/drop_triggers_procedures.sql
  environment:
    rbm_rb_logon_password: "{{ rb_logon_password }}"
  args:
    chdir: "{{ infinys_dir }}"
  register: drop_triggers
  tags:
    - skip_ansible_lint

- debug:
    msg: "{{ drop_triggers.stdout }}"
  when: not ansible_check_mode

- name: Load cache (update gparams)
  include_role:
    name: service_rtcc
    tasks_from: merge_gparams.yaml
  vars:
    merge_gparams_lines:
      - { param_name: "SYSdomainingStrategy", type: "STRING", start_dtm: "to_date('01-JAN-70','DD-MON-RR')", value: "T" }
      - { param_name: "SYSonlineChargingAISInUseBoo", type: "STRING", start_dtm: "to_date('01-JAN-95','DD-MON-RR')", value: "F" }
      - { param_name: "SYSonlineChargingCachesInUseBoo", type: "STRING", start_dtm: "to_date('01-JAN-95','DD-MON-RR')", value: "T" }
      - { param_name: "LCXMbackendDatabaseServiceName", type: "STRING", start_dtm: "to_date(  SYSDATE,  'DD-MON-RR')", value: "{{ be_oracle_service_name }}" }

- name: Copy clean_queues.ksh
  template:
    src: clean_queues.ksh.j2
    dest: "{{ infinys_dir }}/install/clean_queues.ksh"
    owner: "{{ RBM_BE_USER }}"
    group: "{{ RBM_BE_GROUP }}"
    mode: 0755

- name: Clean up queues
  shell: |
    source ./infinys.env
    "{{ infinys_dir }}/install/clean_queues.ksh"
  args:
    chdir: "{{ infinys_dir }}"
  tags:
    - skip_ansible_lint

- name: Copy purge_caches.ksh
  template:
    src: purge_caches.ksh.j2
    dest: "{{ infinys_dir }}/install/purge_caches.ksh"
    owner: "{{ RBM_BE_USER }}"
    group: "{{ RBM_BE_GROUP }}"
    mode: 0755

- name: Purge caches
  register: purge_caches
  shell: |
    source ./infinys.env
    "{{ infinys_dir }}/install/purge_caches.ksh"
  args:
    chdir: "{{ infinys_dir }}"
  tags:
    - skip_ansible_lint

- debug:
    msg: "{{ purge_caches.stdout }}"
  when: not ansible_check_mode
