---
- name: "Prevent run without tags"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display help message
      fail:
        msg: "You must run this playbook with tags!"

- name: "Call cleanup_disconnect_active_sessions"
  hosts: RBM_BE_CONFIG_NODE
  become: true
  remote_user: "{{ rbm_remote_user | default(RBM_BE_USER) }}"
  become_user: "{{ rbm_become_user | default(RBM_BE_USER) }}"
  gather_facts: False
  tags: cleanup_disconnect_active_sessions
  tasks:
    - include_role:
        name: service_rbm
        tasks_from: cleanup_disconnect_active_sessions.yaml
      vars:
        cleanup_disconnect_active_sessions_host_list: "{{ groups['RBM_BE_DB'] }}"
        cleanup_disconnect_active_sessions_file_dest_dir: "{{ infinys_dir }}/scripts"

- name: "Stop ECA"
  hosts: RBM_BE_CONFIG_NODE
  become: true
  remote_user: "{{ rbm_become_user | default(RBM_BE_USER) }}"
  become_user: "{{ rbm_become_user | default(RBM_BE_USER) }}"
  gather_facts: False
  tags:
    - stop_eca
    - restart
  tasks:
    - include_role:
        name: service_rbm
        tasks_from: stop_eca.yaml

- name: "Start ECA"
  hosts: RBM_BE_CONFIG_NODE
  become: true
  remote_user: "{{ rbm_become_user | default(RBM_BE_USER) }}"
  become_user: "{{ rbm_become_user | default(RBM_BE_USER) }}"
  gather_facts: False
  tags:
    - start_eca
    - restart
  tasks:
    - include_role:
        name: service_rbm
        tasks_from: start_eca.yaml
