---
- name: Create config_RTCC.properties file
  template:
    src: config_RTCC.properties.j2
    dest: "{{ infinys_dir }}/AutoInstaller/config_RTCC.properties"
    mode: 0644
  when:
    - rtcc_patch is defined
    - rtcc_patch | bool
